### join the game
POST http://localhost:8032/game/join
Content-Type: application/json

{
  "id": "Gracz 1"
}

### answer question
POST http://localhost:8032/game/answer
Content-Type: application/json

{
  "id": "D"
}
